### ISSUE TITLE
Fake Server -> Greenlight

### ISSUE THREAD

**Issue by snickers2k** [ide/dash-button#59]
I have no clue how this works, but i just found this:

https://github.com/badbeef/Amazon-Dash-Server
http://blog.nemik.net/2015/08/dash-button-corral/

> If your scripts return a 200 OK HTTP response, the Buttons will even light up green to say that all is cool.

Maybe this helps

**Comment by ide** [comment]
Cool find, thanks for sharing. Reading through the technical details I think this shows that faking the server is too hard to be worthwhile -- you need to install custom firmware on your WiFi router so that you can reroute traffic sent to Google DNS and instead spoof the DNS response. 

The second thing is that the Dash button might one day validate the SSL certificates from the server it thinks is `parker-gateway-na.amazon.com`. It sounds like the Dash button doesn't validate them at all (which actually seems OK in this specific scenario -- the worst an attacker could do is make your Dash button light turn green) but if Amazon changed that then the Dash button wouldn't connect to the fake HTTP server anymore.
